apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
      - image: nginx
        name: nginx
