apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-east-1

nodeGroups:
  - name: nodegroup
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyPath: master-key  

      
