apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - image: busybox
    name: liveness
    args:
      - /bin/sh
      - -c
      - touch /tmp/health; sleep 20; rm -rf /tmp/health; sleep 10
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/health
      initialDelaySeconds: 5
      periodSeconds: 5      
